- name: Install dependencies for repo
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: true

- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Add Kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Add Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
    filename: docker

- name: Install Kubernetes dependencies
  ansible.builtin.package:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true
    
- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Remove containerd config
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restart containerd service
  ansible.builtin.systemd:
    path: containerd.service
    state: reloaded

- name: Prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold