- name: Install dependencies for repo
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Add Kubernetes apt repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Add Docker apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker apt repo
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Add Helm apt key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm apt repo
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm-stable-debian

- name: Install Kubernetes dependencies
  ansible.builtin.package:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true
    
- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Remove containerd config
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent
  register: containerd_config

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  when: containerd_config.changed

- name: Create certs directory
  ansible.builtin.file:
    path: /etc/docker/certs.d/docker-registry.corp
    state: directory

- name: Copy docker registry certificate
  ansible.builtin.copy:
    src: ../../../certs/tls.crt
    dest: /etc/docker/certs.d/docker-registry.corp

- name: Install Helm
  ansible.builtin.package:
    name:
      - helm
    state: present

- name: Install Pip
  ansible.builtin.package:
    name:
      - python3-pip
    state: present

- name: Install python modules for Ansible
  pip:
    name:
      - kubernetes
      - docker

- name: Prevent kubeadm from being upgraded
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Prevent kubelet from being upgraded
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Prevent kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold