- name: Push Docker Images
  hosts: master
  become: true

  tasks:
    - name: Copy dockerfile to remote host
      ansible.builtin.copy:
        src: ../dockerfiles
        dest: "/home/{{ ansible_user }}"
      
    - name: Push Jenkins Agent image
      community.docker.docker_image:
          build:
            path: "/home/{{ ansible_user }}/dockerfiles/jenkins-agent"
          name: docker-registry.corp/jenkins-agent
          tag: latest
          push: yes
          source: build