- name: Get join command
  hosts: master
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Bootstrap Kubernetes workers
  hosts: workers
  become: true

  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['master'].join_command }} >> .node_joined"
      args:
        chdir: $HOME
        creates: .node_joined