- name: Bootstrap Kubernetes master
  hosts: master
  become: true
  roles:
    - k8s_dependencies

  tasks:
    - name: Initialize cluster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> .cluster_initialized
      args:
        chdir: "/home/{{ ansible_user }}"
        creates: .cluster_initialized

    - name: Create .kube directory
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
      become: false

    - name: Copy Kubernetes config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Install Flannel
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> .pod_network_setup
      args:
        chdir: $HOME
        creates: .pod_network_setup
      become: false